### ISSUE TITLE
Failed to install with Install-Module

### ISSUE THREAD

**Issue by SebastiaanPolfliet** [MathieuBuisson/cDtc#1]
The resource fails to install because cDtc is overriding existing Get-TargetResources. It's a convention not to export DSC commands in psd1 files. 

### Log

A command with name 'Get-TargetResource' is already available on this system. This module 'cDtc' may override the existing commands. If you still want to install this module 'cDtc', use -AllowClobber parameter.  

---
As extra (and solution) a reference to a deprecated Microsoft resource: https://github.com/PowerShell/xTimeZone/issues/26

If you need more information do not hesitate to contact me (if you prefer I can create the PR too).

**Comment by MathieuBuisson** [comment]
Hi @SebastiaanPolfliet ,

Wow, I wonder how this hasn't come up before !  

It makes sense to **not** export the `*-TargetResource` functions from the module manifest.  

I'm going to make the change.

**Comment by MathieuBuisson** [comment]
I published the fixed module to the Gallery.  
It is available here :  
https://www.powershellgallery.com/packages/cDtc/1.1

**Comment by SebastiaanPolfliet** [comment]
Great! Thanks a lot for taking the time Mathieu!
